#!/bin/bash
set -euf pipefail

lein clean
lein uberjar
scp ./target/uberjar/standalone.jar $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIR/
ssh $DEPLOY_USER@$DEPLOY_HOST systemctl --user restart tictag.service

