CMDS = CMD*
CMD = (BYID|BYLT|PREVPING|SLEEP|HELP|CONT) <EOL>+
HELP = <#'\h'*'help'#'\h'*>
<EOL> = '\n'
CONT = <'!'> TAGS
BYID = ID <' '> TAGS
BYLT = LT <' '> TAGS
ID = #'\d{1,3}'
LT = #'\d\d\d\d\d+'
PREVPING = TAGS
TAGS = !#'^help$' (TAG | DITTO | PLUS | <#'\h+'>)+
TAG = #'[-:.\p{L}][-:.\p{L}0-9]*'
SLEEP = <#'\h'*'sleep'#'\h'*>
DITTO = <'"'>
PLUS = <'+'>