CREATE TABLE users
(
id BIGSERIAL PRIMARY KEY,
username VARCHAR(1024) NOT NULL UNIQUE,
email VARCHAR(1024) NOT NULL UNIQUE,
pass CHAR(98) NOT NULL,
tz TEXT NOT NULL
);

ALTER TABLE pings RENAME TO pings_backup;

CREATE TABLE pings
(
ts TIMESTAMP WITH TIME ZONE NOT NULL,
tz TEXT NOT NULL,
tags TEXT NOT NULL,
user_id BIGINT REFERENCES users(id) NOT NULL
);

ALTER TABLE pings ADD PRIMARY KEY(user_id, ts);
CREATE INDEX ON pings (user_id);

CREATE TABLE slack
(
id BIGSERIAL PRIMARY KEY,
user_id BIGINT UNIQUE REFERENCES users(id),
slack_user_id VARCHAR(1024) NOT NULL,
username VARCHAR(1024) NOT NULL,
encrypted_bot_access_token BYTEA NOT NULL,
encryption_iv BYTEA NOT NULL,
channel_id VARCHAR(1024) NOT NULL
);

CREATE TABLE beeminder
(
id BIGSERIAL PRIMARY KEY,
user_id BIGINT UNIQUE REFERENCES users(id) NOT NULL,
username VARCHAR(1024) NOT NULL,
encrypted_token BYTEA NOT NULL,
encryption_iv BYTEA NOT NULL,
is_enabled BOOLEAN NOT NULL
);

CREATE TABLE beeminder_goals
(
id BIGSERIAL PRIMARY KEY,
beeminder_id BIGINT REFERENCES beeminder(id) NOT NULL,
goal VARCHAR(1024) NOT NULL,
tags TEXT NOT NULL
);

